### ISSUE TITLE
SQLAlchemy / Postgres connection issue

### ISSUE THREAD

**Issue by amuhareb** [florianjuengermann/query-god#2]
hello! i can't get this to run. i'm a total noob so it's likely my fault. it seems that the "backend.modules" across the whole repo can not be resolved.
```
(coremltest) alimuhareb@Alis-MBP query-god-main % python3 app.py
Traceback (most recent call last):
  File "/Users/alimuhareb/Downloads/query-god-main/app.py", line 130, in <module>
    main.toy_test()
  File "/Users/alimuhareb/Downloads/query-god-main/backend/main.py", line 267, in toy_test
    run(history3, capture_output=False)
  File "/Users/alimuhareb/Downloads/query-god-main/backend/main.py", line 96, in run
    db = SQLDatabase.from_uri(db_connection_string)
  File "/Users/alimuhareb/Downloads/query-god-main/backend/modules/database/sql_database.py", line 48, in from_uri
    return cls(create_engine(database_uri), **kwargs)
  File "<string>", line 2, in create_engine
  File "/Users/alimuhareb/opt/miniconda3/envs/coremltest/lib/python3.9/site-packages/sqlalchemy/util/deprecations.py", line 375, in warned
    return fn(*args, **kwargs)
  File "/Users/alimuhareb/opt/miniconda3/envs/coremltest/lib/python3.9/site-packages/sqlalchemy/engine/create.py", line 518, in create_engine
    entrypoint = u._get_entrypoint()
  File "/Users/alimuhareb/opt/miniconda3/envs/coremltest/lib/python3.9/site-packages/sqlalchemy/engine/url.py", line 662, in _get_entrypoint
    cls = registry.load(name)
  File "/Users/alimuhareb/opt/miniconda3/envs/coremltest/lib/python3.9/site-packages/sqlalchemy/util/langhelpers.py", line 343, in load
    raise exc.NoSuchModuleError(
sqlalchemy.exc.NoSuchModuleError: Can't load plugin: sqlalchemy.dialects:postgres
```

would love to know what i'm doing wrong!

**Comment by amuhareb** [comment]
just noticing this is a sort of 'old' repo so maybe it's out of date. things change fast!

**Comment by florianjuengermann** [comment]
Hey, I'm no longer maintaining the repo, but that's what GPT4 says about the issue:
<img width="756" alt="image" src="https://user-images.githubusercontent.com/13962498/233502525-2729033e-ff3d-4e79-ada6-737d2ebfa965.png">

**Comment by florianjuengermann** [comment]
I remember that I set up a supabase postgress to run the code. You probably need to set up a postgress and modify the `.env` file as well.

**Comment by amuhareb** [comment]
Thanks! I’ll probably explore other options. Been diving into making my own
langchain based solution. I’m an amateur so it’s very difficult, but
showing the most signs of success and promise. I might use your repo as
inspiration! Take care
